<!DOCTYPE html>
<html>
<head>
    <title>
        Reset your SEM tools password
    </title>
</head>
<body style="margin: 0px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333333; background-color: #fff;">
<table align="center" width="520px" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
    <tbody>
    <tr>
        <td rowspan="1" colspan="1" valign="top">
            <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                <tr>
                    <td rowspan="1" colspan="1">
                        <div>
                            <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr>
                                    <td style="padding-top:0px;font-family:Helvetica neue,Helvetica,Arial,Verdana,sans-serif;color:#205081;font-size:20px;line-height:32px;text-align:left;font-weight:bold"
                                        rowspan="1" colspan="1" align="left" valign="top">
                                        <span>Reset your SEM tools password</span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="color:#cccccc;padding-top:10px" rowspan="1" colspan="1" valign="top">
                        <hr color="#cccccc" size="1">
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div></div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div>
                            <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr valign="top">
                                    <td style="padding-top:20px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#333333;font-size:14px;line-height:24px;text-align:left;font-weight:none"
                                        rowspan="1" colspan="1" align="left" valign="top">
                                        <span>Hi</span><span> $user_name$</span>,
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="padding-top:10px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#333333;font-size:14px;line-height:20px;text-align:left;font-weight:none"
                        rowspan="1" colspan="1" align="left" valign="top">You've recently asked to reset the password
                        for the following SEM tools account:<br clear="none">
                        <span><a href="mailto:$user_email$" target="_blank">$user_email$</a></span>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="padding-top:10px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#333333;font-size:14px;line-height:20px;text-align:left;font-weight:none"
                        rowspan="1" colspan="1" align="left" valign="top">To update your password, click the button
                        below:
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <table align="left" border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                            <tr>
                                <td style="padding-bottom:20px;padding-top:20px" rowspan="1" colspan="1" align="center">
                                    <a shape="rect" href="$platformUrl$/reset-password?id=$token$" target="_blank">
                                        <div style="background-color:#3572b0;padding:11px;border-radius:5px;display:inline-block">
                                            <span style="font-size:16px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;font-weight:none;color:#ffffff;text-decoration:none;"> Reset my password</span>
                                        </div>
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div>
                            <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr valign="top">
                                    <td style="padding-top:10px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#333333;font-size:14px;line-height:24px;text-align:left;font-weight:none"
                                        rowspan="1" colspan="1" align="left" valign="top">
                                        <span>Regards,</span><br clear="none">
                                        <span>SEM tools</span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div></div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div></div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div></div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div></div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1" align="left" valign="top">
                        <div></div>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td rowspan="1" colspan="1">
            <table align="center" width="520px" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                <tr>
                    <td style="color:#cccccc;padding-top:20px" rowspan="1" colspan="1" valign="top" width="100%">
                        <hr color="#cccccc" size="1">
                    </td>
                </tr>
                <tr>
                    <td rowspan="1" colspan="1">
                        <div>
                            <table align="center" width="520px" bgcolor="#ffffff" border="0" cellpadding="0"
                                   cellspacing="0">
                                <tbody>
                                <tr>
                                    <td style="font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#707070;font-size:12px;text-align:left;font-weight:none"
                                        rowspan="1" colspan="1" align="left" valign="top">
                                        <br clear="none"><span>This message was sent by SEM tools</span><br
                                            clear="none">
                                    </td>
                                    <td style="padding-top:15px;padding-bottom:30px" rowspan="1" colspan="1"
                                        align="right">
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <u></u><u></u>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>