<!DOCTYPE html>
<html>
<head>
  <title>
    Reset your SEM tools password
  </title>
</head>
<body
  style="margin: 0px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333333; background-color: #fff;">
<table align="center" width="520px" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
  <tbody>
  <tr>
    <td rowspan="1" colspan="1" valign="top">
      <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
          <td rowspan="1" colspan="1">
            <div>
              <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                <tr>
                  <td
                    style="padding-top:0px;font-family:Helvetica neue,Helvetica,Arial,Verdana,sans-serif;color:#205081;font-size:20px;line-height:32px;text-align:left;font-weight:bold"
                    rowspan="1" colspan="1" align="left" valign="top">
                    <span>You have joined the SEM Tools</span>
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
          </td>
        </tr>
        <tr>
          <td style="color:#cccccc;padding-top:10px" rowspan="1" colspan="1" valign="top">
            <hr color="#cccccc" size="1">
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div></div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div>
            </div>
          </td>
        </tr>
        <tr>
          <td
            style="padding-top:10px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#333333;font-size:14px;line-height:20px;text-align:left;font-weight:none"
            rowspan="1" colspan="1" align="left" valign="top">Here are your account details:<br clear="none">
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div>
            </div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="center" valign="top">
            <table
              style="table-layout:fixed;border:1px solid #a0a0a2;border-radius:8px;padding:40px 0;margin-top:20px;width:85%;border-collapse:separate"
              border="0" cellpadding="0" cellspacing="0">
              <tbody>
              <tr>
                <td align="center" style="vertical-align:middle">

                  <h3
                    style="font-weight:900;padding-top:10px;margin-bottom:7px;font-size:21px;;margin-top:0;color:#205081">
                    SEM Tools
                  </h3>
                  <h4 style="margin-bottom:2px;font-size:17px;font-weight:400">
                    <strong>Login:</strong> $user_email$
                  </h4>
                  <h4 style="margin-bottom:0;font-size:17px;font-weight:400">
                    <strong>Password:</strong> $user_password$
                  </h4>

                  <table width="102" border="0" cellpadding="0" cellspacing="0"
                         style="text-align:right;display:inline-table;width:auto;vertical-align:top;">
                    <tbody>
                    <tr>
                      <td style="padding-bottom:20px;padding-top:20px" rowspan="1" colspan="1" align="center">
                          <a shape="rect" href="$platformUrl$/login" target="_blank">
                            <div style="background-color:#3572b0;padding:11px;border-radius:5px;display:inline-block;width:80px;">
                              <span
                                style="font-size:16px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#ffffff;text-decoration:none;">
                                Sign In
                              </span>
                            </div>
                          </a>
                      </td>
                    </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
              </tbody>
            </table>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div>
              <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                <tr valign="top">
                  <td
                    style="padding-top:10px;font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#333333;font-size:14px;line-height:24px;text-align:left;font-weight:none"
                    rowspan="1" colspan="1" align="left" valign="top">
                    <span>Regards,</span><br clear="none">
                    <span>SEM tools</span>
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div></div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div></div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div></div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div></div>
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1" align="left" valign="top">
            <div></div>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  <tr>
    <td rowspan="1" colspan="1">
      <table align="center" width="520px" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
          <td style="color:#cccccc;padding-top:20px" rowspan="1" colspan="1" valign="top" width="100%">
            <hr color="#cccccc" size="1">
          </td>
        </tr>
        <tr>
          <td rowspan="1" colspan="1">
            <div>
              <table align="center" width="520px" bgcolor="#ffffff" border="0" cellpadding="0"
                     cellspacing="0">
                <tbody>
                <tr>
                  <td
                    style="font-family:Helvetica,Helvetica neue,Arial,Verdana,sans-serif;color:#707070;font-size:12px;text-align:left;font-weight:none"
                    rowspan="1" colspan="1" align="left" valign="top">
                    <br clear="none"><span>This message was sent by SEM tools</span><br
                    clear="none">
                  </td>
                  <td style="padding-top:15px;padding-bottom:30px" rowspan="1" colspan="1"
                      align="right">
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
            <u></u><u></u>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  </tbody>
</table>
</body>
</html>